name: flutter_play
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  photo_view: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/x.jpg
    - assets/u1.png
    - assets/u2.png
    - assets/u3.png
    - assets/books/uk-en/001.jpg
    - assets/books/uk-en/002.jpg
    - assets/books/uk-en/003.jpg
    - assets/books/uk-en/004.jpg
    - assets/books/uk-en/005.jpg
    - assets/books/uk-en/006.jpg
    - assets/books/uk-en/007.jpg
    - assets/books/uk-en/008.jpg
    - assets/books/uk-en/009.jpg
    - assets/books/uk-en/010.jpg
    - assets/books/uk-en/011.jpg
    - assets/books/uk-en/012.jpg
    - assets/books/uk-en/013.jpg
    - assets/books/uk-en/014.jpg
    - assets/books/uk-en/015.jpg
    - assets/books/uk-en/016.jpg
    - assets/books/uk-en/017.jpg
    - assets/books/uk-en/018.jpg
    - assets/books/uk-en/019.jpg
    - assets/books/uk-en/020.jpg
    - assets/books/uk-en/021.jpg
    - assets/books/uk-en/022.jpg
    - assets/books/uk-en/023.jpg
    - assets/books/uk-en/024.jpg
    - assets/books/uk-en/025.jpg
    - assets/prayerBooklets/uk-en/001.jpg
    - assets/prayerBooklets/uk-en/002.jpg
    - assets/prayerBooklets/uk-en/003.jpg
    - assets/prayerBooklets/uk-en/004.jpg
    - assets/prayerBooklets/uk-en/005.jpg
    - assets/prayerBooklets/uk-en/006.jpg
    - assets/prayerBooklets/uk-en/007.jpg
    - assets/prayerBooklets/uk-en/008.jpg
    - assets/prayerBooklets/uk-en/009.jpg
    - assets/prayerBooklets/uk-en/010.jpg
    - assets/prayerBooklets/uk-en/011.jpg
    - assets/prayerBooklets/uk-en/012.jpg
    - assets/prayerBooklets/uk-en/013.jpg
    - assets/prayerBooklets/uk-en/014.jpg
    - assets/prayerBooklets/uk-en/015.jpg
    - assets/prayerBooklets/uk-en/016.jpg
    - assets/prayerBooklets/uk-en/017.jpg
    - assets/prayerBooklets/uk-en/018.jpg
    - assets/prayerBooklets/uk-en/019.jpg
    - assets/prayerBooklets/uk-en/020.jpg
    - assets/prayerBooklets/uk-en/021.jpg
    - assets/prayerBooklets/uk-en/022.jpg
    - assets/prayerBooklets/uk-en/023.jpg
    - assets/prayerBooklets/uk-en/024.jpg
    - assets/prayerBooklets/uk-en/025.jpg
    - assets/prayerBooklets/uk-en/026.jpg
    - assets/prayerBooklets/uk-en/027.jpg
    - assets/prayerBooklets/uk-en/028.jpg
    - assets/prayerBooklets/uk-en/029.jpg
    - assets/prayerBooklets/uk-en/030.jpg
    - assets/prayerBooklets/uk-en/031.jpg
    - assets/prayerBooklets/uk-en/032.jpg
    - assets/prayerBooklets/uk-en/033.jpg
    - assets/prayerBooklets/uk-en/034.jpg
    - assets/prayerBooklets/uk-en/035.jpg
    - assets/prayerBooklets/uk-en/036.jpg
    - assets/prayerBooklets/uk-en/037.jpg
    - assets/prayerBooklets/uk-en/038.jpg
    - assets/prayerBooklets/uk-en/039.jpg
    - assets/prayerBooklets/uk-en/040.jpg
    - assets/prayerBooklets/uk-en/041.jpg
    - assets/prayerBooklets/uk-en/042.jpg
    - assets/prayerBooklets/uk-en/043.jpg
    - assets/prayerBooklets/uk-en/044.jpg
    - assets/prayerBooklets/uk-en/045.jpg
    - assets/prayerBooklets/uk-en/046.jpg
    - assets/prayerBooklets/uk-en/047.jpg
    - assets/prayerBooklets/uk-en/048.jpg
    - assets/prayerBooklets/uk-en/049.jpg
    - assets/prayerBooklets/uk-en/050.jpg
    - assets/prayerBooklets/uk-en/051.jpg
    - assets/prayerBooklets/uk-en/052.jpg
    - assets/prayerBooklets/uk-en/053.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
